project:
  name: "hack the gap (temporary - name TBD)"
  summary: "AI-powered Zettelkasten that auto-converts students' passive content consumption into active long-term retention via concept extraction and spaced repetition."
  owner: Hugo Ganet
  stage: discovery # discovery | build | alpha | beta | prod | sunset
  tags: [ai-first, hackathon, edtech, zettelkasten, spaced-repetition]

repositories:
  - url: https://github.com/REPLACE_ME

contacts:
  - role: owner
    name: Hugo Ganet
    email: hugoganet@example.com

environments:
  - name: dev
    url: TBD
  - name: prod
    url: TBD

status:
  current_sprint: 0
  last_updated: 2025-11-13

notes:
  naming: "Product name needed - 'hack the gap' is temporary placeholder. Consider: Retention, SyncGraph, ConceptFlow, MemoryMap, etc."
  hackathon: "48-hour MVP timeline - focus on proof of concept, not production quality"

conventions:
  sessions_pattern: "YYYY-MM-DD-session-###.md"
  adr_pattern: "ADR-XXXX-title-kebab-case.md"
  spec_pattern: "feature-title-kebab-case.md"
  story_pattern: "US-####"
  story_filename: "US-####-kebab-case.md"
